[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmds = [
    'python -m venv /opt/venv',
    '. /opt/venv/bin/activate',
    'pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'python main.py'

[variables]
NIXPACKS_PYTHON_VERSION = '3.11'
