
[variables]
NIXPACKS_PYTHON_VERSION = "3.12"

[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
dependsOn = ["setup"]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "python main.py"
