
[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.environmentVariables]]
name = "TELEGRAM_BOT_TOKEN"
value = "${{TELEGRAM_BOT_TOKEN}}"

[environments.production]
variables = {}
